[package]
name = "pnn-approval-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
pnu-primitives = { path = "../../primitives" }
pnn-protocol = { path = "../protocol" }
pnu-subsystem = { path = "../../subsystem" }
pnu-subsystem-util = { path = "../../subsystem-util" }
pdot-primitives = { path = "../../../primitives" }

futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", features = ["std"] }

pnu-subsystem-util = { path = "../../subsystem-util" }
pnu-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
schnorrkel = { version = "0.9.1", default-features = false }
rand_core = "0.5.1" # should match schnorrkel
env_logger = "0.8.2"
log = "0.4.13"
